Added 5 kubernetes subprojects
cncf/clomonitor pull request #1385
Opened 2023-12-15 20:01 UTC by eddie-knight

ref: https://docs.google.com/spreadsheets/d/1Y9hNtp6NaEtp_B0ccwMI06YBdENz3guh93MlPHwdPXM/edit#gid=0

2023-12-15 20:59 UTC, ArangoGutierrez commented
https://github.com/cncf/clomonitor/pull/1378

2023-12-15 20:59 UTC, ArangoGutierrez commented
/assign @tegioz

2023-12-16 16:02 UTC, tegioz requested changes
Thanks @eddie-knight!

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  accepted_at: "2022-04-12"
Could you remove the `accepted_at` and `maturity` fields for the k8s subprojects? (this applies to the rest of entries as well)

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  devstats_url: https://kuberenetes.devstats.cncf.io/
`devstats_url` can be omitted for subprojects if you like. If you prefer to keep it, could you fix the typo? (this happens in the other entries too).

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  devstats_url:
Can you remove the empty `devstats_url` fields? (there are some more below)

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  description: Kubernetes-native Job Queueing.
Could you please remove the dots from the end of the descriptions?

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  category: cluster orchestration and management
The category in this case should be `orchestration`.

2023-12-16 16:02 UTC, tegioz commented on data/cncf.yaml
> +  logo_url: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
Can you use the SVG version of the Kubernetes logo?

`https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png`

2023-12-16 16:16 UTC, eddie-knight commented
@tegioz please take another look, I'm pretty sure I've applied all the requested changes

2023-12-16 16:21 UTC, tegioz commented
Thanks @eddie-knight, it looks great 👍

Would you also like to add the `cloud-provider-aws` (#1384) and `gateway-api` (#1381) subprojects to this PR? They kind of have to fix the same details and we could leave them all ready now 🙂

2023-12-16 17:19 UTC, eddie-knight commented
I went ahead and pulled in the commits from the other PRs and rebased them into a single history here

#1378
#1379 
#1380
#1381
#1382
#1384
#1386

2023-12-16 18:00 UTC, tegioz approved these changes
Thanks! 🥇

2023-12-16 18:00 UTC, merged

2023-12-16 18:19 UTC, afbjorklund commented
Should probably add both `k8s.io/minikube` and `sigs.k8s.io/kind`, since they share some of the container code?

https://github.com/kubernetes/minikube

https://github.com/kubernetes-sigs/kind

The minikube project is older than the creation of the kubernetes-sigs organisation, so it still lives in kubernetes.